#!/usr/bin/env bash
# Cloudflare Pages "build command" entry point.
#
# driftloop has no real build step — this script just stamps the deploy
# commit SHA into version.js so the running app can show what's live.
#
# CF Pages exposes CF_PAGES_COMMIT_SHA during builds; locally it's unset,
# in which case we fall back to 'dev'.

set -euo pipefail

sha="${CF_PAGES_COMMIT_SHA:-dev}"
short="${sha:0:7}"

cat > version.js <<EOF
// Auto-generated by scripts/build.sh on deploy. Do not edit by hand.
export const VERSION = '${short}';
EOF

echo "stamped version.js with ${short}"
